import { storage } from "./storage";
import type { InsertQuestion } from "@shared/schema";

// Sample questions from the 2022-2026 Technician question pool
// In a production app, this would contain all 412 questions
const sampleQuestions: InsertQuestion[] = [
  // T1 - FCC Rules (sample of 6)
  {
    id: "T1A01",
    subelement: "T1A",
    questionText: "Which of the following is part of the Basis and Purpose of the Amateur Radio Service?",
    answerA: "Providing personal radio communications for as many citizens as possible",
    answerB: "Providing communications for international non-profit organizations",
    answerC: "Advancing skills in the technical and communication phases of the radio art",
    answerD: "All these choices are correct",
    correctAnswer: "C",
    explanation: "The FCC defines the Basis and Purpose of amateur radio in Part 97.1 as recognition and enhancement of the value of the amateur service to the public, particularly with respect to providing emergency communications. Advancing skills in both technical and communication aspects is a core purpose, which helps operators develop expertise in radio technology and operating procedures.",
    references: "97.1",
  },
  {
    id: "T1A02",
    subelement: "T1A",
    questionText: "What agency regulates and enforces the rules for the Amateur Radio Service in the United States?",
    answerA: "FEMA",
    answerB: "Homeland Security",
    answerC: "The FCC",
    answerD: "All these choices are correct",
    correctAnswer: "C",
    explanation: "The Federal Communications Commission (FCC) is the government agency responsible for regulating all non-federal radio communications in the United States, including amateur radio. The FCC creates and enforces the rules in Part 97 of the FCC rules.",
    references: "97.1",
  },
  {
    id: "T1B01",
    subelement: "T1B",
    questionText: "What is the ITU?",
    answerA: "An agency of the United States Department of Telecommunications Management",
    answerB: "A United Nations agency for information and communication technology issues",
    answerC: "An independent frequency coordination agency",
    answerD: "A department of the FCC",
    correctAnswer: "B",
    explanation: "The International Telecommunication Union (ITU) is a specialized agency of the United Nations responsible for issues concerning information and communication technologies. It allocates global radio spectrum and satellite orbits, develops technical standards, and works to improve telecommunications infrastructure in developing countries.",
    references: "97.3(a)(4)",
  },
  {
    id: "T1C01",
    subelement: "T1C",
    questionText: "For which license classes are new licenses currently available from the FCC?",
    answerA: "Novice, Technician, General, Amateur Extra",
    answerB: "Technician, Technician Plus, General, Amateur Extra",
    answerC: "Technician, General, Amateur Extra",
    answerD: "Novice, Technician, General, Advanced, Amateur Extra",
    correctAnswer: "C",
    explanation: "The FCC currently issues three classes of amateur radio licenses: Technician (entry level), General (intermediate), and Amateur Extra (highest level). The Novice, Technician Plus, and Advanced license classes have been discontinued, though existing holders may renew those licenses.",
    references: "97.9(a)",
  },
  {
    id: "T1C02",
    subelement: "T1C",
    questionText: "Who may select a desired call sign under the vanity call sign rules?",
    answerA: "Only a licensed amateur with a General or Amateur Extra class license",
    answerB: "Only a licensed amateur with an Amateur Extra class license",
    answerC: "Only a licensed amateur who has been licensed continuously for more than 10 years",
    answerD: "Any licensed amateur",
    correctAnswer: "D",
    explanation: "Any licensed amateur radio operator in the United States, regardless of license class or how long they've been licensed, may apply for a vanity call sign through the FCC's Universal Licensing System (ULS). There is a fee for this service.",
    references: "97.19",
  },
  {
    id: "T1C03",
    subelement: "T1C",
    questionText: "What types of international communications are permitted by an FCC-licensed amateur station?",
    answerA: "Communications incidental to the purposes of the amateur service and remarks of a personal character",
    answerB: "Communications incidental to conducting business or remarks of a personal nature",
    answerC: "Only communications incidental to contest exchanges",
    answerD: "Any communications that would be permitted by an international broadcast station",
    correctAnswer: "A",
    explanation: "Amateur radio operators may engage in international communications that are incidental to the purposes of the amateur service (experimenting, emergency communications, etc.) and personal remarks. Business communications are prohibited. The amateur service is for self-training, technical investigations, and emergency communications, not commercial purposes.",
    references: "97.117",
  },

  // T2 - Operating Procedures (sample of 3)
  {
    id: "T2A01",
    subelement: "T2A",
    questionText: "What is a common repeater frequency offset in the 2 meter band?",
    answerA: "Plus or minus 5 MHz",
    answerB: "Plus or minus 600 kHz",
    answerC: "Plus or minus 500 kHz",
    answerD: "Plus or minus 1 MHz",
    correctAnswer: "B",
    explanation: "In the 2 meter (144-148 MHz) amateur band, the standard repeater offset is plus or minus 600 kHz. This means if a repeater's output frequency is 146.520 MHz, its input frequency would be either 145.920 MHz (minus offset) or 147.120 MHz (plus offset). This offset allows simultaneous transmission and reception on the repeater.",
    references: null,
  },
  {
    id: "T2A02",
    subelement: "T2A",
    questionText: "What is the national calling frequency for FM simplex operations in the 2 meter band?",
    answerA: "146.520 MHz",
    answerB: "145.000 MHz",
    answerC: "432.100 MHz",
    answerD: "446.000 MHz",
    correctAnswer: "A",
    explanation: "146.520 MHz is the nationally recognized calling frequency for FM simplex (direct, non-repeater) communications on the 2 meter band. Operators often monitor this frequency to make initial contact before moving to another frequency for their conversation. This helps coordinate simplex operations and allows operators to find each other.",
    references: null,
  },
  {
    id: "T2B01",
    subelement: "T2B",
    questionText: "What is the most common use of the 'reverse split' function of a VHF/UHF transceiver?",
    answerA: "Reduce power output",
    answerB: "Increase power output",
    answerC: "Listen on a repeater's input frequency",
    answerD: "Listen on a repeater's output frequency",
    correctAnswer: "C",
    explanation: "The reverse split function allows you to listen on the repeater's input frequency (the frequency you normally transmit on). This is useful for hearing stations that are accessing the repeater directly, determining if another station can hear the repeater, or checking if the repeater input frequency is clear before transmitting.",
    references: null,
  },

  // T3 - Radio Wave Characteristics (sample of 3)
  {
    id: "T3A01",
    subelement: "T3A",
    questionText: "What should you do if another operator reports that your station's 2 meter signals were strong just a moment ago, but now they are weak or distorted?",
    answerA: "Change the batteries in your radio to a different type",
    answerB: "Turn on the CTCSS tone",
    answerC: "Ask the other operator to adjust their squelch control",
    answerD: "Try moving a few feet or changing the direction of your antenna",
    correctAnswer: "D",
    explanation: "This is likely caused by multipath interference, where radio signals take different paths to reach the receiving station. These multiple signals can arrive out of phase and cancel each other out or cause distortion. Moving even a short distance or changing antenna orientation can significantly change the multipath pattern and improve signal quality.",
    references: null,
  },
  {
    id: "T3B01",
    subelement: "T3B",
    questionText: "What is the relationship between the electric and magnetic fields of an electromagnetic wave?",
    answerA: "They travel at different speeds",
    answerB: "They are in parallel",
    answerC: "They revolve in opposite directions",
    answerD: "They are at right angles",
    correctAnswer: "D",
    explanation: "In an electromagnetic wave, the electric field and magnetic field are perpendicular (at right angles) to each other and both are perpendicular to the direction of wave propagation. They oscillate in phase with each other and travel at the speed of light. This relationship is fundamental to how radio waves propagate through space.",
    references: null,
  },
  {
    id: "T3C01",
    subelement: "T3C",
    questionText: "What is the ability to communicate using part of a satellite's uplink and downlink in one mode called?",
    answerA: "Dual band mode",
    answerB: "Duplex mode",
    answerC: "Full duplex mode",
    answerD: "Cross band mode",
    correctAnswer: "C",
    explanation: "Full duplex operation allows you to transmit and receive simultaneously, just like a telephone conversation. In satellite communications, you transmit on the uplink frequency while listening to the downlink frequency at the same time. This requires a radio capable of transmitting on one band while receiving on another simultaneously.",
    references: null,
  },

  // T4 - Amateur Radio Practices (sample of 2)
  {
    id: "T4A01",
    subelement: "T4A",
    questionText: "Which of the following is an appropriate power supply rating for a typical 50 watt output mobile FM transceiver?",
    answerA: "24.0 volts at 4 amperes",
    answerB: "13.8 volts at 4 amperes",
    answerC: "24.0 volts at 12 amperes",
    answerD: "13.8 volts at 12 amperes",
    correctAnswer: "D",
    explanation: "Mobile transceivers are designed to operate from a vehicle's 12-volt electrical system. The nominal voltage is 13.8 volts (the typical voltage of a car's charging system). A 50-watt transmitter needs sufficient current capacity - approximately 12 amperes is appropriate to handle the power requirements during transmit and provide some safety margin.",
    references: null,
  },
  {
    id: "T4B01",
    subelement: "T4B",
    questionText: "What may happen if a transmitter is operated with the microphone gain set too high?",
    answerA: "The output power might be too high",
    answerB: "The output signal might become distorted",
    answerC: "The frequency might vary",
    answerD: "The SWR might increase",
    correctAnswer: "B",
    explanation: "If the microphone gain is set too high, it can cause overmodulation, which distorts the transmitted signal. This can make your signal difficult to understand and may cause interference to adjacent frequencies. Proper microphone gain adjustment ensures clear, undistorted audio without overdriving the transmitter's modulation circuit.",
    references: null,
  },

  // T5 - Electrical Principles (sample of 4)
  {
    id: "T5A01",
    subelement: "T5A",
    questionText: "Electrical current is measured in which of the following units?",
    answerA: "Volts",
    answerB: "Watts",
    answerC: "Ohms",
    answerD: "Amperes",
    correctAnswer: "D",
    explanation: "Electric current is the flow of electric charge and is measured in amperes (amps). One ampere represents one coulomb of charge flowing past a point in one second. Volts measure voltage, watts measure power, and ohms measure resistance.",
    references: null,
  },
  {
    id: "T5A02",
    subelement: "T5A",
    questionText: "Electrical power is measured in which of the following units?",
    answerA: "Volts",
    answerB: "Watts",
    answerC: "Ohms",
    answerD: "Amperes",
    correctAnswer: "B",
    explanation: "Electrical power is measured in watts. Power is the rate at which electrical energy is converted to another form of energy (like heat or radio waves). One watt equals one joule per second. Power can be calculated as voltage multiplied by current (P = V × I).",
    references: null,
  },
  {
    id: "T5B01",
    subelement: "T5B",
    questionText: "How many milliamperes is 1.5 amperes?",
    answerA: "15 milliamperes",
    answerB: "150 milliamperes",
    answerC: "1,500 milliamperes",
    answerD: "15,000 milliamperes",
    correctAnswer: "C",
    explanation: "One ampere equals 1,000 milliamperes (mA). Therefore, 1.5 amperes equals 1.5 × 1,000 = 1,500 milliamperes. The prefix 'milli-' means one-thousandth, so a milliampere is one-thousandth of an ampere.",
    references: null,
  },
  {
    id: "T5C01",
    subelement: "T5C",
    questionText: "What is the ability to store energy in an electric field called?",
    answerA: "Inductance",
    answerB: "Resistance",
    answerC: "Tolerance",
    answerD: "Capacitance",
    correctAnswer: "D",
    explanation: "Capacitance is the ability to store energy in an electric field between two conducting plates separated by an insulator (dielectric). Capacitors store energy when voltage is applied across them. Inductance stores energy in a magnetic field, resistance opposes current flow, and tolerance is the acceptable variation in a component's value.",
    references: null,
  },

  // T6 - Electrical Components (sample of 4)
  {
    id: "T6A01",
    subelement: "T6A",
    questionText: "What electrical component opposes the flow of current in a DC circuit?",
    answerA: "Inductor",
    answerB: "Resistor",
    answerC: "Voltmeter",
    answerD: "Transformer",
    correctAnswer: "B",
    explanation: "A resistor opposes or limits the flow of electric current in a circuit. Resistance is measured in ohms and determines how much current will flow for a given voltage according to Ohm's Law (V = I × R). Resistors are used to control current, divide voltage, and dissipate power in circuits.",
    references: null,
  },
  {
    id: "T6B01",
    subelement: "T6B",
    questionText: "What class of electronic components uses a voltage or current signal to control current flow?",
    answerA: "Capacitors",
    answerB: "Inductors",
    answerC: "Resistors",
    answerD: "Transistors",
    correctAnswer: "D",
    explanation: "Transistors use a small voltage or current at one terminal (the base or gate) to control a larger current flow between two other terminals. This makes them useful as amplifiers and electronic switches. Common types include bipolar junction transistors (BJTs) and field-effect transistors (FETs).",
    references: null,
  },
  {
    id: "T6C01",
    subelement: "T6C",
    questionText: "What is the name for standardized representations of components in an electrical wiring diagram?",
    answerA: "Electrical depictions",
    answerB: "Grey sketch",
    answerC: "Schematic symbols",
    answerD: "Component callouts",
    correctAnswer: "C",
    explanation: "Schematic symbols are standardized graphical representations of electrical and electronic components used in circuit diagrams. These symbols allow anyone familiar with electronics to read and understand circuit diagrams regardless of language. Each component type (resistor, capacitor, transistor, etc.) has a unique symbol.",
    references: null,
  },
  {
    id: "T6D01",
    subelement: "T6D",
    questionText: "Which of the following devices or circuits changes an alternating current into a varying direct current signal?",
    answerA: "Transformer",
    answerB: "Rectifier",
    answerC: "Amplifier",
    answerD: "Reflector",
    correctAnswer: "B",
    explanation: "A rectifier converts alternating current (AC) to direct current (DC). It uses diodes to allow current to flow in only one direction, effectively converting the alternating polarity of AC to a pulsating DC. Rectifiers are essential components in power supplies that convert AC from wall outlets to DC needed by electronic devices.",
    references: null,
  },

  // T7 - Practical Circuits (sample of 4)
  {
    id: "T7A01",
    subelement: "T7A",
    questionText: "Which term describes the ability of a receiver to detect the presence of a signal?",
    answerA: "Linearity",
    answerB: "Sensitivity",
    answerC: "Selectivity",
    answerD: "Total Harmonic Distortion",
    correctAnswer: "B",
    explanation: "Sensitivity is a receiver's ability to detect weak signals. It's typically measured as the minimum signal strength needed at the receiver's input to produce a usable output. A more sensitive receiver can detect weaker signals. Selectivity refers to the ability to separate desired signals from unwanted ones.",
    references: null,
  },
  {
    id: "T7B01",
    subelement: "T7B",
    questionText: "What can you do if you are told your FM handheld or mobile transceiver is over-deviating?",
    answerA: "Talk louder into the microphone",
    answerB: "Let the transceiver cool off",
    answerC: "Change to a higher power level",
    answerD: "Talk farther away from the microphone",
    correctAnswer: "D",
    explanation: "Over-deviation occurs when the audio signal is too strong, causing the transmitted signal to deviate too far from the carrier frequency. This can cause distortion and interference to adjacent channels. Moving the microphone farther from your mouth or reducing microphone gain will reduce the audio level and prevent over-deviation.",
    references: null,
  },
  {
    id: "T7C01",
    subelement: "T7C",
    questionText: "What is the primary purpose of a dummy load?",
    answerA: "To prevent an antenna from radiating signals when making tests",
    answerB: "To prevent over-modulation of a transmitter",
    answerC: "To improve the radiation pattern of an antenna",
    answerD: "To improve the signal-to-noise ratio of a receiver",
    correctAnswer: "A",
    explanation: "A dummy load is a non-radiating resistive load that absorbs the transmitter's RF power without radiating it as a signal. This allows you to test and adjust a transmitter without putting a signal on the air. It presents a proper impedance (usually 50 ohms) to the transmitter while dissipating the power as heat.",
    references: null,
  },
  {
    id: "T7D01",
    subelement: "T7D",
    questionText: "Which instrument would you use to measure electric potential or electromotive force?",
    answerA: "An ammeter",
    answerB: "A voltmeter",
    answerC: "A wavemeter",
    answerD: "An ohmmeter",
    correctAnswer: "B",
    explanation: "A voltmeter measures voltage (electric potential or electromotive force) between two points in a circuit. Voltmeters are connected in parallel with the component or circuit being measured. An ammeter measures current, an ohmmeter measures resistance, and a wavemeter measures frequency.",
    references: null,
  },

  // T8 - Signals and Emissions (sample of 4)
  {
    id: "T8A01",
    subelement: "T8A",
    questionText: "Which of the following is a form of amplitude modulation?",
    answerA: "Spread spectrum",
    answerB: "Packet radio",
    answerC: "Single sideband",
    answerD: "Phase shift keying",
    correctAnswer: "C",
    explanation: "Single sideband (SSB) is a form of amplitude modulation where the carrier and one sideband are suppressed, transmitting only one sideband. This is more efficient than full AM because it requires less bandwidth and power. SSB is the primary voice mode used on HF amateur bands.",
    references: null,
  },
  {
    id: "T8B01",
    subelement: "T8B",
    questionText: "Who may be the control operator of a station communicating through an amateur satellite or space station?",
    answerA: "Only an Amateur Extra Class operator",
    answerB: "A General Class licensee or higher licensee who has a satellite operator certification",
    answerC: "Only an Amateur Extra Class operator who is also an AMSAT member",
    answerD: "Any amateur whose license privileges allow them to transmit on the satellite uplink frequency",
    correctAnswer: "D",
    explanation: "Any licensed amateur operator can communicate through an amateur satellite as long as they have privileges on the uplink frequency being used. There are no special license class requirements or certifications needed for satellite operation. The key is having authorization for the frequency you're transmitting on.",
    references: "97.209",
  },
  {
    id: "T8C01",
    subelement: "T8C",
    questionText: "Which of the following methods is used to locate sources of noise interference or jamming?",
    answerA: "Echolocation",
    answerB: "Doppler radar",
    answerC: "Radio direction finding",
    answerD: "Phase locking",
    correctAnswer: "C",
    explanation: "Radio direction finding (RDF) uses directional antennas and specialized receivers to determine the direction a radio signal is coming from. By taking bearings from multiple locations, you can triangulate the source of the signal. This technique is useful for locating sources of interference, finding hidden transmitters, or participating in transmitter hunting activities.",
    references: null,
  },
  {
    id: "T8D01",
    subelement: "T8D",
    questionText: "Which of the following is an example of a digital communications method?",
    answerA: "Single sideband",
    answerB: "PSK31",
    answerC: "FM phone",
    answerD: "Double sideband",
    correctAnswer: "B",
    explanation: "PSK31 (Phase Shift Keying, 31 baud) is a digital mode that uses phase modulation to transmit keyboard-to-keyboard messages. It's very efficient and can work with extremely weak signals. Other digital modes include RTTY, FT8, and packet radio. SSB, FM, and DSB are all analog voice modes.",
    references: null,
  },

  // T9 - Antennas and Feed Lines (sample of 2)
  {
    id: "T9A01",
    subelement: "T9A",
    questionText: "What is a beam antenna?",
    answerA: "An antenna built from aluminum I-beams",
    answerB: "An omnidirectional antenna invented by Clarence Beam",
    answerC: "An antenna that concentrates signals in one direction",
    answerD: "An antenna that reverses the phase of received signals",
    correctAnswer: "C",
    explanation: "A beam antenna (also called a directional antenna) concentrates transmitted and received signals in a particular direction, providing gain in that direction. Common examples include Yagi antennas and parabolic dishes. Beam antennas are useful for long-distance communication and reducing interference from unwanted directions.",
    references: null,
  },
  {
    id: "T9B01",
    subelement: "T9B",
    questionText: "What is a benefit of low SWR?",
    answerA: "Reduced television interference",
    answerB: "Increased signal strength at the receiver",
    answerC: "Effective transfer of RF power from the transmitter to the antenna",
    answerD: "All these choices are correct",
    correctAnswer: "C",
    explanation: "Standing Wave Ratio (SWR) indicates how well the antenna system impedance matches the transmitter output impedance. Low SWR (close to 1:1) means more efficient power transfer from the transmitter to the antenna, with less power being reflected back to the transmitter. High SWR can damage transmitters and reduces the effectiveness of your station.",
    references: null,
  },

  // T0 - Electrical and RF Safety (sample of 3)
  {
    id: "T0A01",
    subelement: "T0A",
    questionText: "Which is a commonly accepted value for the lowest voltage that can cause a dangerous electric shock?",
    answerA: "12 volts",
    answerB: "30 volts",
    answerC: "120 volts",
    answerD: "300 volts",
    correctAnswer: "B",
    explanation: "While any voltage can potentially be dangerous under the right circumstances, 30 volts is commonly accepted as the threshold where electric shock becomes potentially dangerous to humans. Above this voltage, current can flow through the body in amounts that may cause harm. Always treat any voltage source with respect and use proper safety precautions.",
    references: null,
  },
  {
    id: "T0B01",
    subelement: "T0B",
    questionText: "When should members of a tower work team wear a hard hat and safety glasses?",
    answerA: "At all times except when climbing the tower",
    answerB: "At all times except when belted firmly to the tower",
    answerC: "At all times when any work is being done on the tower",
    answerD: "Only when the tower exceeds 30 feet in height",
    correctAnswer: "C",
    explanation: "Safety equipment including hard hats and safety glasses should be worn at all times during any tower work, whether you're climbing, at ground level, or working on the tower structure. Tools, hardware, or debris can fall from any height and cause serious injury. This is standard safety practice for all tower work regardless of tower height.",
    references: null,
  },
  {
    id: "T0C01",
    subelement: "T0C",
    questionText: "What type of radiation are VHF and UHF radio signals?",
    answerA: "Gamma radiation",
    answerB: "Ionizing radiation",
    answerC: "Alpha radiation",
    answerD: "Non-ionizing radiation",
    correctAnswer: "D",
    explanation: "VHF and UHF radio signals are non-ionizing radiation. Unlike ionizing radiation (such as X-rays or gamma rays), non-ionizing radiation doesn't have enough energy to remove electrons from atoms. However, RF energy can still cause biological effects through heating, so it's important to follow FCC exposure guidelines and use appropriate power levels and antenna placement.",
    references: null,
  },
];

export async function seedDatabase() {
  console.log("Starting database seeding...");
  
  try {
    // Seed questions
    console.log(`Seeding ${sampleQuestions.length} sample questions...`);
    await storage.seedQuestions(sampleQuestions);
    console.log("Questions seeded successfully!");

    console.log("Database seeding completed!");
    console.log("\nNote: This is a sample dataset with representative questions.");
    console.log("A production application would include all 412 questions from the");
    console.log("2022-2026 Technician question pool available from NCVEC.");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

// Run seed if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase()
    .then(() => {
      console.log("Seeding completed successfully");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
}
